flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-language
- yi-frontend-vty
- yi-keymap-vim
extra-deps: []
resolver: lts-8.18
build:
 library-profiling: false
 executable-profiling: false

# needed for macOS
# flags:
#   gtk:
#     have-quartz-gtk: true