name: yi-mode-javascript
version: 0.15.0
synopsis: Yi editor javascript mode
maintainer: Yi developers <yi-devel@googlegroups.com>
license: GPL-2
github: yi-editor/yi
category: Yi

ghc-options: -Wall -ferror-spans

extra-source-files:
  - src/Yi/Lexer/common.hsinc

dependencies:
    - base >= 4.8 && < 5
    - array
    - binary >= 0.7
    - data-default
    - dlist
    - filepath
    - microlens-platform
    - mtl
    - text
    - yi-core
    - yi-rope

library:
    source-dirs: src
    exposed-modules:
      - Yi.Config.Default.JavaScriptMode
      - Yi.Mode.JavaScript
      - Yi.Syntax.JavaScript
      - Yi.Verifier.JavaScript
      - Yi.Lexer.JavaScript
    build-tools:
      - alex >= 3.0.3 && < 3.2.0 || >= 3.2.1

include-dirs:
    - src/Yi/Lexer